"use client";

import { useEffect, useState } from "react";

const stages = [{ title: "Depodan sevk", detail: "Malzeme depodan çıkarken", key: "SHIPMENT" }, { title: "Fabrika teslimi", detail: "Fabrika teslim alırken", key: "FACTORY_RECEIPT" }, { title: "Ürün teslimi", detail: "Fabrika bitmiş ürünü verirken", key: "PRODUCTION_DELIVERY" }, { title: "Depoya giriş", detail: "Ürün depoya konulurken", key: "WAREHOUSE_RECEIPT" }];

export default function DeliveriesPage() {
  const [files, setFiles] = useState<Record<string, string>>({}); const [photoUrls, setPhotoUrls] = useState<Record<string, string>>({}); const [party, setParty] = useState<string | null>(null); const [error, setError] = useState("");
  useEffect(() => { setParty(new URLSearchParams(window.location.search).get("party")); }, []);
  async function upload(stage: string, file: File) { setError(""); const form = new FormData(); form.append("file", file); form.append("stage", stage); form.append("relatedType", "delivery"); form.append("relatedId", party || "manual"); const response = await fetch("/api/evidence", { method: "POST", body: form }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Fotoğraf yüklenemedi."); return; } setFiles((current) => ({ ...current, [stage]: file.name })); setPhotoUrls((current) => ({ ...current, [stage]: body.storagePath })); }
  return <div className="min-h-screen px-6 py-6 lg:px-10"><div className="mx-auto max-w-6xl"><div className="eyebrow">GÜNLÜK İŞLER · KANIT</div><h1 className="mt-2 text-3xl font-semibold">Teslimat kanıtları</h1><p className="mt-2 max-w-2xl text-sm text-muted">{party ? `${party} için oluşturulan teslimat işi ve fotoğraf adımları.` : "Sevk, fabrika teslimi, bitmiş ürün ve depoya giriş fotoğrafla kayıt altına alınır."}</p>{error && <div className="mt-5 rounded-lg border border-danger/30 bg-danger/10 px-4 py-3 text-sm text-danger">{error}</div>}<div className="mt-8 grid gap-4 md:grid-cols-2">{stages.map((stage, index) => <div className="card p-5" key={stage.key}><div className="flex items-start justify-between"><div><div className="eyebrow">ADIM 0{index + 1}</div><h2 className="mt-2 text-lg font-medium">{stage.title}</h2><p className="mt-1 text-xs text-muted">{stage.detail}</p></div><div className={`grid h-9 w-9 place-items-center rounded-full ${files[stage.key] ? "bg-success/15 text-success" : "bg-accent/10 text-accent"}`}>{files[stage.key] ? "✓" : "▣"}</div></div>{photoUrls[stage.key] && <img src={photoUrls[stage.key]} alt={stage.title} className="mt-4 h-40 w-full rounded-lg object-cover" />}<label className="mt-5 flex cursor-pointer items-center justify-center rounded-lg border border-dashed border-line bg-[#0d1219] px-4 py-5 text-center text-xs text-muted transition hover:border-accent hover:text-accent"><input className="sr-only" type="file" accept="image/*" capture="environment" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(stage.key, file); }} />{files[stage.key] ? <span className="text-success">{files[stage.key]} · Kalıcı kanıt eklendi</span> : <span>Fotoğraf çek veya yükle<br /><span className="mt-1 inline-block text-[10px]">JPG, PNG · mobil kamerayı kullanabilir</span></span>}</label></div>)}</div><div className="mt-6 rounded-xl border border-accent/25 bg-accent/5 p-5 text-sm leading-6 text-muted"><span className="font-medium text-accent">Kayıt kuralı:</span> Fotoğraf sunucuda saklanır ve kim tarafından, ne zaman, hangi adım için yüklendi bilgisiyle veritabanına yazılır.</div></div></div>;
}
