"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
type Payment = { id: string; partyName: string; amount: number; currency: string; direction: "PAYMENT" | "COLLECTION"; description?: string | null; createdAt: string };
export default function FinancePage() {
  const [items, setItems] = useState<Payment[]>([]); const [party, setParty] = useState(""); const [form, setForm] = useState({ partyName: "", amount: "", currency: "TRY", direction: "PAYMENT", description: "" }); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async () => { const response = await fetch("/api/modules/finance"); if (response.ok) setItems(await response.json()); };
  useEffect(() => { setParty(new URLSearchParams(window.location.search).get("party") ?? ""); void load(); }, []);
  const filtered = useMemo(() => party ? items.filter((item) => item.partyName.toLocaleLowerCase("tr-TR").includes(party.toLocaleLowerCase("tr-TR"))) : items, [party, items]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); const response = await fetch("/api/modules/finance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "İşlem eklenemedi."); return; } setItems((current) => [body, ...current]); setForm({ partyName: "", amount: "", currency: "TRY", direction: "PAYMENT", description: "" }); setMessage("Cari hareketi kaydedildi."); };
  const balance = filtered.reduce((total, item) => total + (item.direction === "PAYMENT" ? Number(item.amount) : -Number(item.amount)), 0);
  return <div className="min-h-screen px-6 py-6 lg:px-10"><div className="mx-auto max-w-6xl"><div className="eyebrow">CARİ VE KAYITLAR · FİNANS</div><h1 className="mt-2 text-3xl font-semibold">{party ? `${party} cari hesabı` : "Cari hesaplar"}</h1><p className="mt-2 text-sm text-muted">Ödemeler, tahsilatlar ve kişi bazlı bakiye geçmişi.</p><form onSubmit={submit} className="card mt-6 grid gap-3 p-5 sm:grid-cols-5"><input required placeholder="Kişi / firma" value={form.partyName} onChange={(e) => setForm({ ...form, partyName: e.target.value })} className="rounded-lg border border-line bg-[#0d1219] px-3 py-2 text-sm" /><input required type="number" min="0.01" step="0.01" placeholder="Tutar" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} className="rounded-lg border border-line bg-[#0d1219] px-3 py-2 text-sm" /><select value={form.direction} onChange={(e) => setForm({ ...form, direction: e.target.value })} className="rounded-lg border border-line bg-[#0d1219] px-3 py-2 text-sm"><option value="PAYMENT">Ödeme</option><option value="COLLECTION">Tahsilat</option></select><select value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value })} className="rounded-lg border border-line bg-[#0d1219] px-3 py-2 text-sm"><option>TRY</option><option>USD</option></select><button className="rounded-lg bg-accent px-3 py-2 text-sm font-bold text-ink">Hareket ekle</button></form>{(message || error) && <div className={`mt-4 text-sm ${error ? "text-danger" : "text-success"}`}>{error || message}</div>}<div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="card p-5"><div className="eyebrow">Seçili cari</div><div className="mt-2 text-lg font-medium">{party || "Tümü"}</div></div><div className="card p-5"><div className="eyebrow">Net bakiye hareketi</div><div className={`mt-2 text-3xl ${balance > 0 ? "text-danger" : "text-success"}`}>{Math.abs(balance).toLocaleString("tr-TR")}</div></div><div className="card p-5"><div className="eyebrow">İşlem sayısı</div><div className="mt-2 text-3xl text-accent">{filtered.length}</div></div></div><div className="card mt-6 overflow-hidden"><div className="border-b border-line px-5 py-4 text-sm font-medium">Hareket geçmişi</div>{filtered.length === 0 ? <div className="p-10 text-center text-sm text-muted">Henüz cari hareketi yok.</div> : <div className="divide-y divide-line">{filtered.map((item) => <div className="flex flex-wrap items-center justify-between gap-4 px-5 py-4" key={item.id}><div><div className="text-sm font-medium">{item.partyName}</div><div className="mt-1 text-xs text-muted">{item.description || ""} · {new Date(item.createdAt).toLocaleString("tr-TR")}</div></div><div className={item.direction === "PAYMENT" ? "text-sm text-danger" : "text-sm text-success"}>{item.direction === "PAYMENT" ? "Ödeme" : "Tahsilat"} · {Number(item.amount).toLocaleString("tr-TR")} {item.currency}</div></div>)}</div>}</div></div></div>;
}
