const stats = [
  { label: "Toplam sipariş", value: "24", note: "+%12 bu ay", tone: "text-accent" },
  { label: "Üretimdeki işler", value: "8", note: "3 fabrika aktif", tone: "text-success" },
  { label: "Bekleyen teslimat", value: "5", note: "2 onay bekliyor", tone: "text-accent" },
  { label: "Kritik stok", value: "3", note: "Acil aksiyon gerekli", tone: "text-danger" },
];

const alerts = [
  ["Valf", "Mevcut 87 / Minimum 500", "Kritik stok", "text-danger"],
  ["Fabrika 1 teslimatı", "500 adet malzeme kontrol bekliyor", "Onay bekliyor", "text-accent"],
  ["A Kozmetik siparişi", "180 adet ürün eksik", "Üretim önerilir", "text-accent"],
];

export default function DashboardPage() {
  return <div className="min-h-screen px-6 py-6 lg:px-10">
    <header className="mb-8 flex flex-wrap items-start justify-between gap-5"><div><div className="eyebrow mb-2">Cumartesi, 12 Eylül 2026</div><h1 className="m-0 text-3xl font-semibold tracking-tight">Günaydın, yönetici.</h1><p className="mt-2 text-sm text-muted">Operasyon merkezindeki son durumu buradan takip edin.</p></div><div className="flex items-center gap-3"><div className="rounded-xl border border-line bg-panel px-4 py-3"><div className="eyebrow">USD / TRY</div><div className="mt-1 text-lg font-semibold">₺41,82 <span className="ml-1 text-xs text-success">+0,4%</span></div></div><div className="grid h-11 w-11 place-items-center rounded-full border border-line bg-panel text-sm font-bold text-accent">AY</div></div></header>
    <section className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => <div className="card p-5" key={stat.label}><div className="eyebrow">{stat.label}</div><div className={`mt-3 text-3xl font-semibold ${stat.tone}`}>{stat.value}</div><div className="mt-2 text-xs text-muted">{stat.note}</div></div>)}</section>
    <section className="mb-6 grid gap-6 xl:grid-cols-[1.45fr_1fr]"><div className="card grid-lines p-6"><div className="mb-8 flex items-start justify-between"><div><div className="eyebrow">Stok varlığı</div><div className="mt-2 text-3xl font-semibold">₺4.821.350</div></div><div className="rounded-lg border border-line px-3 py-2 text-right"><div className="eyebrow">USD karşılığı</div><div className="mt-1 font-medium text-accent">$115.295</div></div></div><div className="grid h-40 grid-cols-12 items-end gap-2 border-b border-line">{[42,55,48,67,61,72,64,80,75,86,78,94].map((height, index) => <div key={index} className="rounded-t bg-accent/70" style={{ height: `${height}%` }} />)}</div><div className="mt-3 flex justify-between text-[10px] text-muted"><span>Oca</span><span>Mar</span><span>May</span><span>Tem</span><span>Eyl</span></div></div><div className="card p-6"><div className="mb-5 flex items-center justify-between"><div><div className="eyebrow">Fabrika görünümü</div><div className="mt-2 text-lg font-semibold">Aktif operasyonlar</div></div><span className="text-xs text-accent">Tümünü gör →</span></div><div className="space-y-4">{[["Fabrika 1", "3 aktif üretim", "500 adet malzeme"], ["Fabrika 2", "1 aktif üretim", "Teslimat bekliyor"], ["Fabrika 3", "Hazır", "Normal"]].map(([name, status, detail]) => <div className="flex items-center justify-between border-b border-line pb-4 last:border-0 last:pb-0" key={name}><div><div className="text-sm font-medium">{name}</div><div className="mt-1 text-xs text-muted">{status}</div></div><div className="text-right text-xs text-accent">{detail}</div></div>)}</div></div></section>
    <section className="grid gap-6 xl:grid-cols-[1fr_1.45fr]"><div className="card p-6"><div className="mb-5 flex items-center justify-between"><div><div className="eyebrow">Acil işler</div><div className="mt-2 text-lg font-semibold">Aksiyon gerekenler</div></div><span className="rounded-full bg-danger/10 px-2 py-1 text-xs text-danger">3 açık</span></div><div className="space-y-3">{alerts.map(([title, detail, status, tone]) => <div className="rounded-lg border border-line bg-[#0d1219] p-3" key={title}><div className="flex items-center justify-between"><span className="text-sm font-medium">{title}</span><span className={`text-[11px] ${tone}`}>{status}</span></div><div className="mt-1 text-xs text-muted">{detail}</div></div>)}</div></div><div className="card p-6"><div className="mb-5 flex items-center justify-between"><div><div className="eyebrow">Son hareketler</div><div className="mt-2 text-lg font-semibold">Operasyon akışı</div></div><span className="text-xs text-accent">Aktivite günlüğü →</span></div><div className="space-y-5">{[["14:32", "Mehmet", "500 şişe → Fabrika 1", "Sevk oluşturuldu"], ["14:41", "Ahmet", "Malzeme teslimatını onayladı", "Teslimat #SHP-0024"], ["14:45", "Ahmet", "4 fotoğraf yükledi", "Teslimat kanıtı"], ["15:08", "Sistem", "A Kozmetik siparişi güncellendi", "180 adet eksik"]].map(([time, actor, action, detail]) => <div className="flex gap-4" key={time + actor}><div className="w-12 pt-0.5 text-xs text-muted">{time}</div><div className="relative flex-1 border-l border-line pl-4"><div className="text-sm"><span className="font-medium">{actor}</span> <span className="text-muted">· {action}</span></div><div className="mt-1 text-xs text-accent">{detail}</div></div></div>)}</div></div></section>
  </div>;
}
