"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

type Action = { label: string; href: string };
type Message = { from: "assistant" | "user"; text: string; actions?: Action[] };

const suggestions = ["Bugün ne yapacağız?", "Eksik stokları kontrol et", "Fabrika işlerini özetle", "Bekleyen talepler ne durumda?"];

export function Assistant() {
  const [open, setOpen] = useState(false); const [text, setText] = useState(""); const [loading, setLoading] = useState(false); const [messages, setMessages] = useState<Message[]>([{ from: "assistant", text: "Merhaba. Operasyon sekreterin olarak buradayım. Bugünün planını, eksik stokları, fabrika işlerini ve bekleyen teslimatları birlikte takip edebiliriz." }]);
  async function ask(question: string) { if (!question.trim() || loading) return; setMessages((current) => [...current, { from: "user", text: question }]); setText(""); setLoading(true); try { const response = await fetch("/api/assistant", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: question }) }); const body = await response.json(); setMessages((current) => [...current, { from: "assistant", text: body.reply ?? body.error ?? "Şu an yanıt veremiyorum.", actions: body.actions }]); } catch { setMessages((current) => [...current, { from: "assistant", text: "Bağlantıyı kontrol eder misin? Veritabanına ulaşamadığım için operasyon özetini çıkaramadım." }]); } finally { setLoading(false); } }
  function submit(event: FormEvent) { event.preventDefault(); void ask(text); }
  return <div className="assistant-root"><div className={`assistant-panel ${open ? "assistant-panel-open" : ""}`}><div className="assistant-header"><div className="assistant-avatar"><span className="assistant-avatar-core">✦</span><i /><i /><i /></div><div><div className="text-sm font-semibold">Stoks sekreter</div><div className="assistant-status"><span /> Sistem verilerini izliyor</div></div><button onClick={() => setOpen(false)} className="assistant-close" aria-label="Asistanı kapat">×</button></div><div className="assistant-body"><div className="assistant-code-layer">0101 1100 0011<br />1010 0110 1001<br />0100 1110 0101<br />0011 1010 1100</div><div className="assistant-messages">{messages.map((message, index) => <div className={`assistant-message ${message.from === "user" ? "assistant-message-user" : ""}`} key={`${message.from}-${index}`}><div className="whitespace-pre-line">{message.text}</div>{message.actions && <div className="mt-3 flex flex-wrap gap-2">{message.actions.map((action) => <Link className="assistant-action" href={action.href} key={action.href}>{action.label} →</Link>)}</div>}</div>)}{loading && <div className="assistant-message"><span className="assistant-typing"><i /><i /><i /></span> Verileri tarıyorum...</div>}</div></div><div className="assistant-suggestions">{suggestions.map((suggestion) => <button key={suggestion} onClick={() => void ask(suggestion)} disabled={loading}>{suggestion}</button>)}</div><form className="assistant-form" onSubmit={submit}><input value={text} onChange={(event) => setText(event.target.value)} placeholder="Bugün ne yapacağız?" /><button type="submit" disabled={loading || !text.trim()} aria-label="Gönder">↑</button></form></div><button className={`assistant-orb ${open ? "assistant-orb-open" : ""}`} onClick={() => setOpen((value) => !value)} aria-label="Stoks sekreterini aç"><span className="assistant-orb-ring ring-one" /><span className="assistant-orb-ring ring-two" /><span className="assistant-orb-core">✦</span><span className="assistant-orb-label">SEKRETER</span></button></div>;
}
