"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type RecordItem = Record<string, unknown>;
type Line = { productId: string; quantity: string; unitPrice: string };
function text(item: RecordItem | undefined, key: string) { return item?.[key] === null || item?.[key] === undefined ? "" : String(item[key]); }
function nestedName(value: unknown) { return value && typeof value === "object" && "name" in value ? String((value as { name: string }).name) : String(value ?? "—"); }

export default function OrdersPage() {
  const [orders, setOrders] = useState<RecordItem[]>([]); const [customers, setCustomers] = useState<RecordItem[]>([]); const [products, setProducts] = useState<RecordItem[]>([]); const [customerId, setCustomerId] = useState(""); const [currency, setCurrency] = useState("TRY"); const [lines, setLines] = useState<Line[]>([{ productId: "", quantity: "1", unitPrice: "" }]); const [query, setQuery] = useState(""); const [showForm, setShowForm] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { const [orderResponse, customerResponse, productResponse] = await Promise.all([fetch("/api/orders"), fetch("/api/modules/customers"), fetch("/api/modules/products")]); const orderBody = await orderResponse.json(); const customerBody = await customerResponse.json(); const productBody = await productResponse.json(); if (orderResponse.ok) setOrders(orderBody); else setError(orderBody.error ?? "Siparişler alınamadı."); if (customerResponse.ok) setCustomers(customerBody); if (productResponse.ok) setProducts(productBody); }
  useEffect(() => { void load(); }, []);
  const total = useMemo(() => lines.reduce((sum, line) => sum + (Number(line.quantity) || 0) * (Number(line.unitPrice) || 0), 0), [lines]);
  const filteredOrders = orders.filter((order) => !query.trim() || JSON.stringify(order).toLocaleLowerCase("tr-TR").includes(query.trim().toLocaleLowerCase("tr-TR")));
  function addLine() { setLines([...lines, { productId: "", quantity: "1", unitPrice: "" }]); }
  function updateLine(index: number, key: keyof Line, value: string) { setLines(lines.map((line, lineIndex) => lineIndex === index ? { ...line, [key]: value } : line)); }
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setMessage(""); const response = await fetch("/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customerId, currency, items: lines }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Sipariş oluşturulamadı."); return; } setMessage("Sipariş ve ürün satırları kaydedildi."); setCustomerId(""); setLines([{ productId: "", quantity: "1", unitPrice: "" }]); setShowForm(false); await load(); }
  return <div className="min-h-screen px-6 py-6 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">GÜNLÜK İŞLER · SİPARİŞLER</div><h1 className="mt-2 text-3xl font-semibold">Siparişler</h1><p className="mt-2 text-sm leading-6 text-muted">Müşterinin istediği ürünleri, adetleri ve fiyatları tek siparişte yönetin.</p></div><button onClick={() => setShowForm(!showForm)} className="rounded-lg bg-accent px-4 py-2.5 text-sm font-bold text-ink">{showForm ? "Kapat" : "Yeni sipariş"}</button></div>{message && <div className="mt-5 rounded-lg border border-success/30 bg-success/10 px-4 py-3 text-sm text-success">{message}</div>}{error && <div className="mt-5 rounded-lg border border-danger/30 bg-danger/10 px-4 py-3 text-sm text-danger">{error}</div>}
    {showForm && <form onSubmit={submit} className="card mt-6 p-5"><div className="grid gap-4 sm:grid-cols-3"><label className="block"><span className="mb-2 block text-xs text-muted">Müşteri</span><select required value={customerId} onChange={(event) => setCustomerId(event.target.value)} className="w-full rounded-lg border border-line bg-[#0d1219] px-3 py-2.5 text-sm"><option value="">Müşteri seçin</option>{customers.map((customer) => <option value={text(customer, "id")} key={text(customer, "id")}>{text(customer, "name")}</option>)}</select></label><label className="block"><span className="mb-2 block text-xs text-muted">Para birimi</span><select value={currency} onChange={(event) => setCurrency(event.target.value)} className="w-full rounded-lg border border-line bg-[#0d1219] px-3 py-2.5 text-sm"><option>TRY</option><option>USD</option></select></label><div className="rounded-lg border border-accent/20 bg-accent/5 p-3"><div className="text-xs text-muted">Sipariş toplamı</div><div className="mt-1 text-xl font-semibold text-accent">{total.toLocaleString("tr-TR", { minimumFractionDigits: 2 })} {currency}</div></div></div><div className="mt-6 flex items-center justify-between"><div className="text-sm font-medium">Ürünler</div><button type="button" onClick={addLine} className="rounded-lg border border-line px-3 py-2 text-xs text-accent">+ Ürün satırı</button></div><div className="mt-3 space-y-3">{lines.map((line, index) => <div className="grid gap-3 rounded-lg border border-line bg-[#0d1219] p-3 sm:grid-cols-[1fr_130px_150px_36px]" key={index}><select required value={line.productId} onChange={(event) => updateLine(index, "productId", event.target.value)} className="rounded-lg border border-line bg-[#111821] px-3 py-2.5 text-sm"><option value="">Ürün seçin</option>{products.map((product) => <option value={text(product, "id")} key={text(product, "id")}>{text(product, "name")} · {text(product, "sku")}</option>)}</select><input required min="0.001" step="0.001" type="number" value={line.quantity} onChange={(event) => updateLine(index, "quantity", event.target.value)} className="rounded-lg border border-line bg-[#111821] px-3 py-2.5 text-sm" placeholder="Adet" /><input required min="0.01" step="0.01" type="number" value={line.unitPrice} onChange={(event) => updateLine(index, "unitPrice", event.target.value)} className="rounded-lg border border-line bg-[#111821] px-3 py-2.5 text-sm" placeholder="Birim fiyat" /><button type="button" disabled={lines.length === 1} onClick={() => setLines(lines.filter((_, lineIndex) => lineIndex !== index))} className="rounded-lg border border-danger/30 text-danger disabled:opacity-30">×</button></div>)}</div><button className="mt-6 w-full rounded-lg bg-accent px-4 py-3 text-sm font-bold text-ink">Siparişi ve ürünleri kaydet</button></form>}
    <section className="card mt-6 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-line px-5 py-4"><div><span className="text-sm font-medium">Sipariş kayıtları</span><span className="ml-3 text-xs text-muted">{filteredOrders.length} kayıt</span></div><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full rounded-lg border border-line bg-[#0d1219] px-3 py-2 text-sm sm:w-72" placeholder="Sipariş, müşteri veya ürün ara..." /></div>{filteredOrders.length === 0 ? <div className="p-10 text-center text-sm text-muted">Henüz sipariş yok.</div> : <div className="divide-y divide-line">{filteredOrders.map((order) => <div className="px-5 py-5" key={text(order, "id")}><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-sm font-medium">{text(order, "orderNo") || "Sipariş"} · {nestedName(order.customer)}</div><div className="mt-1 text-xs text-muted">Durum: {text(order, "status")} · {text(order, "createdAt")}</div></div><div className="text-lg font-semibold text-accent">{Number(order.total ?? 0).toLocaleString("tr-TR", { minimumFractionDigits: 2 })} {text(order, "currency")}</div></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{Array.isArray(order.items) && (order.items as RecordItem[]).map((item, index) => <div className="rounded-lg border border-line bg-[#0d1219] px-3 py-2 text-xs" key={String(item.id ?? index)}><span className="font-medium">{nestedName(item.product)}</span><span className="ml-2 text-muted">{text(item, "quantity")} adet × {text(item, "unitPrice")} {text(order, "currency")}</span></div>)}</div></div>)}</div>}</section>
  </div></div>;
}
