"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";

type Item = { id?: string; [key: string]: unknown };
type Field = [name: string, label: string, type: string];
type ModuleConfig = { title: string; description: string; fields: Field[] };

const categories = ["Valf", "Kapak", "Bilezik", "Aksesuar", "Şişe", "Kutu", "Esans", "Etiket", "Diğer"];
const modules: Record<string, ModuleConfig> = {
  orders: { title: "Siparişler", description: "Müşteri siparişlerini kaydedin ve takip edin.", fields: [["customerId", "Müşteri ID", "text"], ["total", "Toplam tutar", "number"], ["currency", "Para birimi", "text"]] },
  production: { title: "Üretim işleri", description: "Fabrikaya verilecek işleri oluşturun.", fields: [["title", "İş adı", "text"], ["factoryName", "Fabrika", "text"], ["quantity", "Miktar", "number"], ["notes", "Not", "text"]] },
  shipments: { title: "Sevk ve teslimat", description: "Depo-fabrika sevk kayıtlarını oluşturun.", fields: [["fromName", "Nereden", "text"], ["toName", "Nereye", "text"], ["itemSummary", "İçerik", "text"], ["quantity", "Miktar", "number"], ["notes", "Not", "text"]] },
  materials: { title: "Malzemeler", description: "Valf, kapak, bilezik, aksesuar, esans ve diğer malzemeleri konumuyla kaydedin.", fields: [["name", "Malzeme adı", "text"], ["sku", "Malzeme kodu / SKU", "text"], ["category", "Kategori", "text"], ["unit", "Birim", "text"], ["minimumStock", "Minimum stok", "number"], ["criticalStock", "Kritik stok", "number"], ["supplier", "Tedarikçi", "text"], ["warehouseId", "Depo ID", "text"], ["locationCode", "Stok kodu / konum", "text"], ["shelfCode", "Raf kodu", "text"], ["quantity", "Başlangıç miktarı", "number"], ["unitCost", "Birim maliyeti", "number"], ["photoPath", "Fotoğraf yolu / URL", "text"]] },
  products: { title: "Ürünler", description: "Bitmiş ürün kartlarını yönetin.", fields: [["name", "Ürün adı", "text"], ["sku", "SKU", "text"], ["brand", "Marka", "text"], ["barcode", "Barkod", "text"], ["volumeMl", "Hacim (ml)", "number"], ["salePrice", "Satış fiyatı", "number"], ["currency", "Para birimi", "text"]] },
  warehouses: { title: "Depolar", description: "Depolarınızı oluşturun.", fields: [["name", "Depo adı", "text"]] },
  customers: { title: "Müşteriler", description: "Müşteri ve cari kartlarını ekleyin.", fields: [["name", "Müşteri adı", "text"], ["contact", "Yetkili kişi", "text"], ["phone", "Telefon", "text"], ["address", "Adres", "text"], ["currency", "Para birimi", "text"], ["notes", "Not", "text"]] },
  factories: { title: "Fason fabrikalar", description: "Fabrikaları ve iletişim bilgilerini kaydedin.", fields: [["name", "Fabrika adı", "text"], ["contact", "Yetkili kişi", "text"], ["phone", "Telefon", "text"], ["address", "Adres", "text"], ["notes", "Not", "text"]] },
  "stock-movements": { title: "Stok özeti", description: "Stok giriş, çıkış ve maliyet hareketlerini yönetin.", fields: [["warehouseId", "Depo ID", "text"], ["materialId", "Malzeme ID", "text"], ["quantity", "Miktar (+ giriş / - çıkış)", "number"], ["locationCode", "Konum kodu", "text"], ["shelfCode", "Raf kodu", "text"], ["unitCost", "Birim maliyeti", "number"], ["description", "Açıklama", "text"]] },
  invoices: { title: "Faturalar", description: "Satış faturası kayıtlarını oluşturun ve takip edin.", fields: [["customerId", "Müşteri ID", "text"], ["subtotal", "Ara toplam", "number"], ["tax", "Vergi", "number"], ["total", "Genel toplam", "number"], ["currency", "Para birimi", "text"], ["notes", "Not", "text"]] },
  activity: { title: "Aktivite geçmişi", description: "Sistemdeki işlemlerin denetim izlerini görüntüleyin.", fields: [] },
  settings: { title: "Ayarlar", description: "Sistem bağlantı durumunu görüntüleyin.", fields: [] },
};

function display(value: unknown) { return typeof value === "object" && value !== null && "name" in value ? String((value as { name: string }).name) : String(value ?? "—"); }
function rowSummary(item: Item) { return Object.entries(item).filter(([key]) => !["id", "updatedAt", "createdAt", "components", "orders", "items", "stocks", "users"].includes(key)).slice(0, 7).map(([key, value]) => `${key}: ${display(value)}`).join(" · "); }

export default function ModulePage() {
  const params = useParams<{ slug?: string[] }>();
  const key = params.slug?.[0] ?? "";
  const config = modules[key];
  const [items, setItems] = useState<Item[]>([]); const [form, setForm] = useState<Record<string, string>>({}); const [query, setQuery] = useState(""); const [editingId, setEditingId] = useState("");
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [showForm, setShowForm] = useState(false); const [showMaterialDetails, setShowMaterialDetails] = useState(false);
  const load = async () => { setLoading(true); const response = await fetch(`/api/modules/${key}`); const body = await response.json(); if (response.ok) setItems(Array.isArray(body) ? body as Item[] : [body as Item]); else setError(body.error ?? "Veriler alınamadı."); setLoading(false); };
  useEffect(() => { if (config) void load(); else setLoading(false); }, [key]);
  const title = config?.title ?? "Modül";
  const fields = config?.fields ?? [];
  const visibleFields = fields.filter(([name]) => key !== "materials" || showMaterialDetails || ["name", "category", "unit"].includes(name));
  const filteredItems = useMemo(() => { const normalized = query.trim().toLocaleLowerCase("tr-TR"); return normalized ? items.filter((item) => Object.values(item).some((value) => display(value).toLocaleLowerCase("tr-TR").includes(normalized))) : items; }, [items, query]);
  const startNew = () => { setForm({}); setEditingId(""); setShowForm(true); setShowMaterialDetails(false); setMessage(""); setError(""); };
  const startEdit = (item: Item) => { const next: Record<string, string> = {}; for (const [name] of fields) next[name] = item[name] === null || item[name] === undefined ? "" : String(item[name]); setForm(next); setEditingId(item.id ?? ""); setShowForm(true); setShowMaterialDetails(key !== "materials"); setMessage(""); setError(""); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); setMessage(""); const editing = Boolean(editingId); const response = await fetch(`/api/modules/${key}`, { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing ? { ...form, id: editingId } : form) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Kayıt kaydedilemedi."); return; } setForm({}); setEditingId(""); setShowForm(false); setMessage(editing ? "Kayıt güncellendi." : "Kayıt oluşturuldu."); await load(); };
  const remove = async (id: string) => { if (!window.confirm("Bu kayıt silinsin mi? Bağlı stok veya hareket varsa silme engellenir.")) return; setError(""); const response = await fetch(`/api/modules/${key}?id=${encodeURIComponent(id)}`, { method: "DELETE" }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Kayıt silinemedi."); return; } setMessage("Kayıt silindi."); await load(); };
  if (!config) return <div className="min-h-screen px-6 py-6 lg:px-10"><div className="mx-auto max-w-5xl"><h1 className="text-3xl font-semibold">{title}</h1><div className="card mt-8 p-6 text-sm text-muted">Bilinmeyen modül.</div></div></div>;
  return <div className="min-h-screen px-6 py-6 lg:px-10"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">OPERASYON MODÜLÜ</div><h1 className="mt-2 text-3xl font-semibold">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">{config.description}</p></div>{fields.length > 0 && <button onClick={showForm ? () => setShowForm(false) : startNew} className="rounded-lg bg-accent px-4 py-2.5 text-sm font-bold text-ink">{showForm ? "Kapat" : "Yeni kayıt ekle"}</button>}</div>{message && <div className="mt-5 rounded-lg border border-success/30 bg-success/10 px-4 py-3 text-sm text-success">{message}</div>}{error && <div className="mt-5 rounded-lg border border-danger/30 bg-danger/10 px-4 py-3 text-sm text-danger">{error}</div>}
    {showForm && <form onSubmit={submit} className="card mt-6 grid gap-4 p-5 sm:grid-cols-2"><div className="sm:col-span-2 text-sm font-medium">{editingId ? "Kaydı düzenle" : "Yeni kayıt"}</div>{visibleFields.map(([name, label, type]) => <label className="block" key={name}><span className="mb-2 block text-xs text-muted">{label}</span>{name === "category" ? <select value={form[name] ?? ""} onChange={(event) => setForm({ ...form, [name]: event.target.value })} className="w-full rounded-lg border border-line bg-[#0d1219] px-3 py-2.5 text-sm"><option value="">Kategori seçin</option>{categories.map((category) => <option key={category}>{category}</option>)}</select> : <input type={type} value={form[name] ?? ""} onChange={(event) => setForm({ ...form, [name]: event.target.value })} className="w-full rounded-lg border border-line bg-[#0d1219] px-3 py-2.5 text-sm outline-none focus:border-accent" required={key === "materials" ? name === "name" : !["notes", "supplier", "brand", "barcode", "contact", "phone", "address", "factoryName", "photoPath", "description", "locationCode", "shelfCode"].includes(name)} />}</label>)}{key === "materials" && <button type="button" onClick={() => setShowMaterialDetails(!showMaterialDetails)} className="sm:col-span-2 text-left text-xs text-accent hover:underline">{showMaterialDetails ? "− Detayları gizle" : "+ Depo, raf, maliyet ve stok detaylarını ekle"}</button>}<button className="sm:col-span-2 rounded-lg bg-accent px-4 py-3 text-sm font-bold text-ink">{editingId ? "Değişiklikleri kaydet" : key === "materials" ? "Malzemeyi hemen ekle" : "Kaydet"}</button></form>}
    <section className="card mt-6 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-line px-5 py-4"><div><span className="text-sm font-medium">Kayıtlar</span><span className="ml-3 text-xs text-muted">{loading ? "Yükleniyor..." : `${filteredItems.length} / ${items.length} kayıt`}</span></div>{!loading && items.length > 0 && <input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full rounded-lg border border-line bg-[#0d1219] px-3 py-2 text-sm sm:w-72" placeholder="Kayıtlarda ara..." />}</div>{!loading && filteredItems.length === 0 ? <div className="p-10 text-center text-sm text-muted">{query ? "Aramanızla eşleşen kayıt yok." : "Henüz kayıt yok."}</div> : <div className="divide-y divide-line">{filteredItems.map((item) => <div className="flex flex-wrap items-center justify-between gap-4 px-5 py-4" key={item.id ?? JSON.stringify(item)}><div className="min-w-0 flex-1"><div className="text-sm font-medium">{display(item.name ?? item.title ?? item.orderNo ?? item.jobNo ?? item.shipmentNo ?? item.invoiceNo ?? item.sku ?? item.action ?? "Sistem durumu")}</div><div className="mt-1 text-xs leading-5 text-muted">{rowSummary(item)}</div></div>{fields.length > 0 && item.id && <div className="flex shrink-0 gap-2"><button onClick={() => startEdit(item)} className="rounded-lg border border-line px-3 py-2 text-xs text-accent hover:bg-[#171e29]">Düzenle</button>{["materials", "products", "warehouses", "factories", "customers"].includes(key) && <button onClick={() => void remove(item.id!)} className="rounded-lg border border-danger/30 px-3 py-2 text-xs text-danger hover:bg-danger/10">Sil</button>}</div>}</div>)}</div>}</section>
  </div></div>;
}
