"use client";

import { FormEvent, useEffect, useState } from "react";

const modules: Record<string, { title: string; description: string; fields: Array<[string, string, string]> }> = {
  orders: { title: "Siparişler", description: "Müşteri siparişlerini kaydedin ve üretime aktarılacak işleri takip edin.", fields: [["customerId", "Müşteri ID", "text"], ["total", "Toplam tutar", "number"], ["currency", "Para birimi (TRY/USD)", "text"]] },
  production: { title: "Üretim işleri", description: "Fabrikaya verilecek işleri oluşturun ve durumlarını takip edin.", fields: [["title", "İş adı", "text"], ["factoryName", "Fabrika", "text"], ["quantity", "Miktar", "number"], ["notes", "Not", "text"]] },
  shipments: { title: "Sevk ve teslimat", description: "Depo-fabrika arasındaki sevk kayıtlarını oluşturun.", fields: [["fromName", "Nereden", "text"], ["toName", "Nereye", "text"], ["itemSummary", "İçerik", "text"], ["quantity", "Miktar", "number"], ["notes", "Not", "text"]] },
  materials: { title: "Malzemeler", description: "Esans, şişe, kutu ve diğer girdileri tek tek ekleyin.", fields: [["name", "Malzeme adı", "text"], ["sku", "SKU", "text"], ["category", "Kategori", "text"], ["unit", "Birim", "text"], ["minimumStock", "Minimum stok", "number"], ["criticalStock", "Kritik stok", "number"], ["supplier", "Tedarikçi", "text"]] },
  products: { title: "Ürünler", description: "Bitmiş ürün kartlarını ve satış bilgilerini yönetin.", fields: [["name", "Ürün adı", "text"], ["sku", "SKU", "text"], ["brand", "Marka", "text"], ["barcode", "Barkod", "text"], ["volumeMl", "Hacim (ml)", "number"], ["salePrice", "Satış fiyatı", "number"], ["currency", "Para birimi (TRY/USD)", "text"]] },
  warehouses: { title: "Depolar", description: "Depolarınızı oluşturun; stok hareketleri bu merkezlere bağlanır.", fields: [["name", "Depo adı", "text"]] },
  customers: { title: "Müşteriler", description: "Müşteri ve cari kartlarını sisteme ekleyin.", fields: [["name", "Müşteri adı", "text"], ["contact", "Yetkili kişi", "text"], ["phone", "Telefon", "text"], ["address", "Adres", "text"], ["currency", "Para birimi (TRY/USD)", "text"], ["notes", "Not", "text"]] },
  factories: { title: "Fason fabrikalar", description: "Fabrikaları, iletişim bilgilerini ve aktif işlerini kaydedin.", fields: [["name", "Fabrika adı", "text"], ["contact", "Yetkili kişi", "text"], ["phone", "Telefon", "text"], ["address", "Adres", "text"], ["notes", "Not", "text"]] },
};

function valueOf(value: unknown) { return typeof value === "object" && value !== null && "name" in value ? String((value as { name: string }).name) : String(value ?? "—"); }
function summary(item: Record<string, unknown>) { return Object.entries(item).filter(([key]) => !["id", "updatedAt", "createdAt", "components", "orders", "items", "stocks", "users"].includes(key)).slice(0, 5).map(([key, value]) => `${key}: ${valueOf(value)}`).join(" · "); }

export default function ModulePage() {
  const key = typeof window === "undefined" ? "" : window.location.pathname.split("/")[1] || "";
  const config = modules[key];
  const [items, setItems] = useState<Record<string, unknown>[]>([]);
  const [form, setForm] = useState<Record<string, string>>({});
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const load = async () => { setLoading(true); const response = await fetch(`/api/modules/${key}`); const body = await response.json(); if (response.ok) setItems(body); else setError(body.error ?? "Veriler alınamadı."); setLoading(false); };
  useEffect(() => { if (config) void load(); else setLoading(false); }, [key]);
  const title = config?.title ?? (key === "stock-movements" ? "Stok özeti" : key === "activity" ? "Aktivite geçmişi" : key === "settings" ? "Ayarlar" : "Modül");
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); setMessage(""); const response = await fetch(`/api/modules/${key}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Kayıt eklenemedi."); return; } setItems((current) => [body, ...current]); setForm({}); setShowForm(false); setMessage("Kayıt oluşturuldu."); };
  if (!config) return <div className="min-h-screen px-6 py-6 lg:px-10"><div className="mx-auto max-w-5xl"><div className="eyebrow">STOKS</div><h1 className="mt-2 text-3xl font-semibold">{title}</h1><p className="mt-3 text-sm text-muted">Bu bölüm sistem kayıtlarını gösterir.</p><div className="card mt-8 p-6 text-sm text-muted">Bu modül için veri bağlantısı hazırlanıyor. Diğer temel modüller aktif olarak kullanılabilir.</div></div></div>;
  return <div className="min-h-screen px-6 py-6 lg:px-10"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">OPERASYON MODÜLÜ</div><h1 className="mt-2 text-3xl font-semibold">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">{config.description}</p></div><button onClick={() => setShowForm(!showForm)} className="rounded-lg bg-accent px-4 py-2.5 text-sm font-bold text-ink">{showForm ? "Kapat" : "Yeni kayıt ekle"}</button></div>{message && <div className="mt-5 rounded-lg border border-success/30 bg-success/10 px-4 py-3 text-sm text-success">{message}</div>}{error && <div className="mt-5 rounded-lg border border-danger/30 bg-danger/10 px-4 py-3 text-sm text-danger">{error}</div>}{showForm && <form onSubmit={submit} className="card mt-6 grid gap-4 p-5 sm:grid-cols-2">{config.fields.map(([name, fieldLabel, type]) => <label className="block" key={name}><span className="mb-2 block text-xs text-muted">{fieldLabel}</span><input type={type} value={form[name] ?? ""} onChange={(event) => setForm({ ...form, [name]: event.target.value })} className="w-full rounded-lg border border-line bg-[#0d1219] px-3 py-2.5 text-sm outline-none focus:border-accent" required={!["notes", "supplier", "brand", "barcode", "contact", "phone", "address", "factoryName"].includes(name)} /></label>)}<button className="sm:col-span-2 rounded-lg bg-accent px-4 py-3 text-sm font-bold text-ink">Kaydet</button></form>}<section className="card mt-6 overflow-hidden"><div className="flex items-center justify-between border-b border-line px-5 py-4"><span className="text-sm font-medium">Kayıtlar</span><span className="text-xs text-muted">{loading ? "Yükleniyor..." : `${items.length} kayıt`}</span></div>{!loading && items.length === 0 ? <div className="p-10 text-center text-sm text-muted">Henüz kayıt yok. İlk kaydı ekleyerek başlayın.</div> : <div className="divide-y divide-line">{items.map((item) => <div className="px-5 py-4" key={String(item.id)}><div className="text-sm font-medium">{valueOf(item.name ?? item.title ?? item.orderNo ?? item.jobNo ?? item.shipmentNo ?? item.sku)}</div><div className="mt-1 text-xs leading-5 text-muted">{summary(item)}</div></div>)}</div>}</section></div></div>;
}
