"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

export function LoginPage() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [returnTo, setReturnTo] = useState("/");
  useEffect(() => { setReturnTo(new URLSearchParams(window.location.search).get("returnTo") ?? "/"); }, []);
  async function login(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); if (!response.ok) { const body = await response.json() as { error?: string }; setError(body.error ?? "Giriş yapılamadı."); setLoading(false); return; } router.replace(returnTo); router.refresh(); }
  return <main className="login-page"><div className="login-glow login-glow-one" /><div className="login-glow login-glow-two" /><div className="login-grid" /><div className="login-layout"><section className="login-intro"><div className="login-brand"><span>S</span><div><div className="text-sm font-black tracking-[.28em]">STOKS</div><div className="text-[10px] uppercase tracking-[.2em] text-white/45">Operasyon merkezi</div></div></div><div className="mt-16 max-w-xl"><div className="login-kicker"><span className="login-pulse" /> Üretimden teslimata tek merkez</div><h1 className="login-title">İşinizi görünür kılan <span>akıllı operasyon.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-white/55">Stoklarınızı, fabrikalarınızı, teslimat kanıtlarını ve cari hareketleri tek bir akışta yönetin.</p></div><div className="mt-12 grid max-w-xl gap-3 sm:grid-cols-3"><div className="login-feature"><b>01</b><span>Stok kontrolü</span></div><div className="login-feature"><b>02</b><span>Fotoğraflı teslim</span></div><div className="login-feature"><b>03</b><span>Cari takibi</span></div></div></section><section className="login-card"><div className="mb-8"><div className="text-xs font-bold uppercase tracking-[.2em] text-accent">Güvenli giriş</div><h2 className="mt-3 text-3xl font-semibold tracking-tight">Tekrar hoş geldin</h2><p className="mt-2 text-sm leading-6 text-white/45">Operasyon paneline devam etmek için hesabına giriş yap.</p></div><form className="space-y-5" onSubmit={login}><label className="block"><span className="mb-2 block text-xs font-medium text-white/70">E-posta adresi</span><input className="login-input" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="ornek@sirket.com" autoComplete="email" required /></label><label className="block"><span className="mb-2 block text-xs font-medium text-white/70">Şifre</span><input className="login-input" type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="••••••••" autoComplete="current-password" required /></label>{error && <div className="rounded-xl border border-red-400/25 bg-red-400/10 px-3 py-2.5 text-xs text-red-300">{error}</div>}<button className="login-button" type="submit" disabled={loading}>{loading ? "Kontrol ediliyor..." : "Panele giriş yap"}<span>→</span></button></form><div className="mt-7 border-t border-white/10 pt-5 text-xs leading-5 text-white/40"><span>İlk kez mi kuruyorsun?</span> <Link href="/setup" className="font-semibold text-accent hover:underline">İlk admin hesabını oluştur →</Link></div></section></div><div className="login-footer">STOKS <span>·</span> Güvenli operasyon altyapısı</div></main>;
}
