"use client";

import { FormEvent, useEffect, useState } from "react";

type Item = Record<string, unknown>;
const value = (item: Item | undefined, key: string) => item?.[key] == null ? "" : String(item[key]);
const statusText: Record<string, string> = { NEW: "Yeni", STOCK_CHECK: "Stok kontrolü", PREPARING: "Hazırlanıyor", QUEUED: "Bekliyor", IN_PROGRESS: "Üretimde", COMPLETED: "Tamamlandı", REQUESTED: "Talep edildi", IN_TRANSIT: "Yolda" };

export default function OperationsPage() {
  const [data, setData] = useState<Record<string, unknown>>({}); const [showJob, setShowJob] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [job, setJob] = useState({ title: "", quantity: "", factoryName: "", costPerUnit: "", orderId: "", productId: "" });
  const load = async () => { const response = await fetch("/api/operations"); const body = await response.json(); if (response.ok) setData(body); else setError(body.error ?? "Operasyon verisi alınamadı."); };
  useEffect(() => { void load(); }, []);
  const orders = Array.isArray(data.orders) ? data.orders as Item[] : []; const requirements = Array.isArray(data.requirements) ? data.requirements as Item[] : []; const production = Array.isArray(data.production) ? data.production as Item[] : []; const requests = Array.isArray(data.requests) ? data.requests as Item[] : []; const shipments = Array.isArray(data.shipments) ? data.shipments as Item[] : []; const shortages = requirements.filter((item) => Number(item.shortage) > 0);
  async function requestMaterial(item: Item) { const response = await fetch("/api/operations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "create-request", materialId: value(item, "materialId"), quantity: value(item, "shortage"), unit: value(item, "unit"), notes: `Sipariş ihtiyacı: ${(item.orders as string[] | undefined)?.join(", ") ?? ""}` }) }); const body = await response.json(); if (!response.ok) setError(body.error ?? "Talep oluşturulamadı."); else { setMessage(`${value(item, "name")} için malzeme talebi oluşturuldu.`); await load(); } }
  async function createJob(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/operations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "create-job", ...job }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Üretim işi oluşturulamadı."); return; } setMessage("Fabrika üretim işi oluşturuldu."); setJob({ title: "", quantity: "", factoryName: "", costPerUnit: "", orderId: "", productId: "" }); setShowJob(false); await load(); }
  async function updateJob(id: string, status: string) { const response = await fetch("/api/operations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "update-job", id, status }) }); const body = await response.json(); if (!response.ok) setError(body.error ?? "İş durumu güncellenemedi."); else await load(); }
  return <div className="min-h-screen px-6 py-6 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">OPERASYON MERKEZİ</div><h1 className="mt-2 text-3xl font-semibold">Siparişten teslime tek akış</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Siparişleri, reçeteye göre malzeme ihtiyacını, fabrika işlerini ve teslimatları aynı ekrandan yönetin.</p></div><button onClick={() => setShowJob(!showJob)} className="rounded-lg bg-accent px-4 py-2.5 text-sm font-bold text-ink">{showJob ? "Kapat" : "Fabrikaya iş ver"}</button></div>{message && <div className="mt-5 rounded-lg border border-success/30 bg-success/10 px-4 py-3 text-sm text-success">{message}</div>}{error && <div className="mt-5 rounded-lg border border-danger/30 bg-danger/10 px-4 py-3 text-sm text-danger">{error}</div>}
    <div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Aktif sipariş", orders.length], ["Malzeme açığı", shortages.length], ["Fabrika işi", production.length], ["Açık talep", requests.filter((item) => ["REQUESTED", "APPROVED", "ORDERED", "IN_TRANSIT"].includes(value(item, "status"))).length], ["Sevkiyat", shipments.length]].map(([label, count]) => <div className="card p-5" key={String(label)}><div className="eyebrow">{label}</div><div className="mt-3 text-3xl font-semibold text-accent">{count}</div></div>)}</div>
    {showJob && <form onSubmit={createJob} className="card mt-6 grid gap-4 p-5 sm:grid-cols-2"><div className="sm:col-span-2 text-sm font-medium">Fabrikaya yeni iş ata</div><input required placeholder="İş adı / ürün" value={job.title} onChange={(event) => setJob({ ...job, title: event.target.value })} className="rounded-lg border border-line bg-[#0d1219] p-3 text-sm" /><input required type="number" min="1" placeholder="Üretilecek adet" value={job.quantity} onChange={(event) => setJob({ ...job, quantity: event.target.value })} className="rounded-lg border border-line bg-[#0d1219] p-3 text-sm" /><input required placeholder="Fabrika adı" value={job.factoryName} onChange={(event) => setJob({ ...job, factoryName: event.target.value })} className="rounded-lg border border-line bg-[#0d1219] p-3 text-sm" /><input type="number" min="0" step="0.01" placeholder="Birim fason maliyeti (USD/TRY)" value={job.costPerUnit} onChange={(event) => setJob({ ...job, costPerUnit: event.target.value })} className="rounded-lg border border-line bg-[#0d1219] p-3 text-sm" /><select value={job.orderId} onChange={(event) => setJob({ ...job, orderId: event.target.value })} className="rounded-lg border border-line bg-[#0d1219] p-3 text-sm"><option value="">Siparişle ilişkilendir (opsiyonel)</option>{orders.map((item) => <option key={value(item, "id")} value={value(item, "id")}>{value(item, "orderNo")} · {value(item, "customer")}</option>)}</select><button className="rounded-lg bg-accent p-3 text-sm font-bold text-ink">İşi oluştur ve kuyruğa al</button></form>}
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_1fr]"><section className="card overflow-hidden"><div className="border-b border-line px-5 py-4"><div className="text-sm font-medium">Siparişe göre malzeme kontrolü</div><div className="mt-1 text-xs text-muted">Ürün reçeteleri tanımlıysa sipariş miktarıyla mevcut stok karşılaştırılır.</div></div>{requirements.length === 0 ? <div className="p-8 text-sm text-muted">Henüz reçeteli sipariş ihtiyacı oluşmadı. Ürün reçetesine valf, kapak, bilezik, etiket, kutu, separatör, esans, alkol, hazır su gibi malzemeleri ekleyin.</div> : <div className="divide-y divide-line">{requirements.map((item) => <div className="flex flex-wrap items-center justify-between gap-4 px-5 py-4" key={value(item, "materialId")}><div><div className="text-sm font-medium">{value(item, "name")}</div><div className="mt-1 text-xs text-muted">Gerekli: {value(item, "required")} · Mevcut: {value(item, "stock")} {value(item, "unit")}</div></div>{Number(item.shortage) > 0 ? <button onClick={() => void requestMaterial(item)} className="rounded-lg border border-accent/40 px-3 py-2 text-xs text-accent">Talep oluştur · {value(item, "shortage")}</button> : <span className="rounded-full border border-success/30 px-3 py-1 text-xs text-success">Stok yeterli</span>}</div>)}</div>}</section><section className="card overflow-hidden"><div className="border-b border-line px-5 py-4"><div className="text-sm font-medium">Fabrika işleri</div><div className="mt-1 text-xs text-muted">Fabrika yalnızca kendisine atanan işleri kabul eder, eksik notu bırakır ve teslim eder.</div></div>{production.length === 0 ? <div className="p-8 text-sm text-muted">Henüz fabrika işi yok.</div> : <div className="divide-y divide-line">{production.map((item) => <div className="px-5 py-4" key={value(item, "id")}><div className="flex flex-wrap justify-between gap-3"><div><div className="text-sm font-medium">{value(item, "jobNo")} · {value(item, "title")}</div><div className="mt-1 text-xs text-muted">{value(item, "factoryName")} · {value(item, "quantity")} adet · Birim maliyet: {value(item, "costPerUnit") || "—"}</div></div><span className="rounded-full border border-accent/30 px-3 py-1 text-xs text-accent">{statusText[value(item, "status")] ?? value(item, "status")}</span></div>{value(item, "missingNotes") && <div className="mt-3 rounded-lg border border-warning/30 bg-warning/10 p-3 text-xs text-warning">Eksik notu: {value(item, "missingNotes")}</div>}<div className="mt-3 flex flex-wrap gap-2">{value(item, "status") === "QUEUED" && <button onClick={() => void updateJob(value(item, "id"), "IN_PROGRESS")} className="rounded-lg border border-line px-3 py-2 text-xs text-accent">İşi başlat</button>}{value(item, "status") === "IN_PROGRESS" && <button onClick={() => void updateJob(value(item, "id"), "COMPLETED")} className="rounded-lg border border-success/30 px-3 py-2 text-xs text-success">Teslim edildi olarak işaretle</button>}</div></div>)}</div>}</section></div>
  </div></div>;
}
